package edu.java.exception02;


/*
 * try-catch 구문을 사용한 예외 처리:
 * 
 * try{
 * 		정상적인 상황에서 실행할 코드들;
 * } catch(Exception타입 변수이름) {
 * 		비정상적인 상황(예외 상황)에서 실행할 코드들;
 * } finally{
 * 		try 블록 또는 catch 블록이 끝난 후 실행할 코드들;
 * }
 */
public class ExceptionMain02 {

	public static void main(String[] args) {
		
		System.out.println("try 구문을 사용한 예외 처리");
		
		System.out.println("프로그램 종료");
		
	}
}
